Highlight downloaded regions
YacGroup/yacguide pull request #280
Opened 2021-12-20 14:22 UTC by paetz

Resolves #278

2021-12-20 20:51 UTC, chrgernoe requested changes
* I would not add the tick in front of the downloaded regions. In my eyes this makes the layout a bit nervous. My suggestions would be to add an empty box in front of each item but mark it as check, if downloaded. 
* Please don't introduce a "completely" new color. There is a link in the color definition file that describes the color scheme which is used in the app. Please keep with this color either within the primary or secondary color "space".

2021-12-20 20:52 UTC, chrgernoe commented on app/src/main/res/values/colors.xml
> +    <color name="colorDownloaded">#ddeeff</color>
Use a more general name so that this color can also be used on other places in the app.

2021-12-21 09:52 UTC, paetz commented
> * Please don't introduce a "completely" new color. There is a link in the color definition file that describes the color scheme which is used in the app. Please keep with this color either within the primary or secondary color "space".

Hm, I tried the secondary color, but this is a bit confusing since grey color means "prohibited" in the other views. I'll choose a light color from our "Indigo" color scheme and define it as a new color, I hope that's ok.

2021-12-21 21:50 UTC, chrgernoe approved these changes

2021-12-22 08:24 UTC, merged