Added modern float action buttons
YacGroup/yacguide pull request #362
Opened 2022-11-30 09:58 UTC by paetz

Resolves #298

2022-12-04 15:15 UTC, chrgernoe requested changes
All apps I know place this kind of button in the right bottom corner. I would also place it there. At the current position it somehow looks not OK.

2022-12-04 15:15 UTC, chrgernoe commented on app/src/main/res/layout/route_description.xml
> +            app:layout_constraintBottom_toBottomOf="parent"/>
```suggestion
            app:layout_constraintBottom_toBottomOf="parent"
            style="@style/floatingActionButtonStyle"/>
```
Add a style to file `style.xml`:
```xml
<style name="floatingActionButtonStyle">
    <item name="tint">@color/colorOnPrimary</item>
    <item name="backgroundTint">@color/colorPrimary</item>
</style>
```
I'm not fully happy with the style but for now it is OK.

2022-12-06 15:14 UTC, paetz commented
> All apps I know place this kind of button in the right bottom corner. I would also place it there. At the current position it somehow looks not OK.

This is not possible right now since it would then cover the Edit and Delete buttons in the Partner list. Solution would be to make Edit/Delete available via Swipe and remove those buttons

2022-12-08 21:33 UTC, chrgernoe commented
Adding via gestures is in my eyes not very intuitive. Is it possible to hide the button by default and make it visible only in this view?

2022-12-09 12:46 UTC, paetz commented
> Adding via gestures is in my eyes not very intuitive. Is it possible to hide the button by default and make it visible only in this view?

You misunderstood me. Solution is Edit/Delete on swiping while the ActionButton for adding is in the right down corner (overlaying the partner list in that area), just as you desired.

2022-12-09 19:12 UTC, chrgernoe commented
Deleting via swipe gesture is fine for me but editing via swipe is also not so nice in my eyes. Another suggestion would be the long press on a partner. This would then open a menu for edit and delete. See Threema app on the chat list.

Just that I understand it right. The action button is used in the partner view also to add a new partner? 

> overlaying the partner list in that area

I can live with that. It is the same in other apps.

2022-12-22 23:07 UTC, chrgernoe approved these changes

2022-12-23 08:23 UTC, merged