Added swiping gestures to partner activity for edit and delete
YacGroup/yacguide pull request #367
Opened 2022-12-13 15:33 UTC by paetz

Resolves #366

2022-12-15 23:24 UTC, chrgernoe requested changes

2022-12-15 23:24 UTC, chrgernoe commented on app/src/main/java/com/yacgroup/yacguide/list_adapters/SwipeController.kt
> +                c.drawColor(Color.YELLOW)
Please make the context object available in the class and use a color defined in the color resource file.

2022-12-16 11:38 UTC, paetz commented on app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt
> +                    additionalInfo = "(${ascendPartnerCount.get(it.id, 0)})",
yes, otherwise you would have complained that there is so much open space per item :)

2022-12-17 11:10 UTC, chrgernoe approved these changes

2022-12-17 20:29 UTC, merged